# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlmOKYxU407dvj1waY60AD2D0gss4chC

## Import necessary library
"""

import pandas as pd

"""## Data dictionary with predefined financial information (Example)

"""

data = {
    "Microsoft": {
        "Total Revenue": "245,122 million",
        "Net Income Growth": "21.80%",
        "Assets Growth": "24.32%",
        "Liabilities Growth": "18.44%",
        "Cash Flow Growth": "35.36%"
    },
    "Tesla": {
        "Total Revenue": "96,773 million",
        "Net Income Growth": "18.96%",
        "Assets Growth": "29.49%",
        "Liabilities Growth": "18.03%",
        "Cash Flow Growth": "-9.97%"
    },
    "Apple": {
        "Total Revenue": "383,285 million",
        "Net Income Growth": "-2.81%",
        "Assets Growth": "-0.05%",
        "Liabilities Growth": "-3.86%",
        "Cash Flow Growth": "-9.50%"
    }
}

"""## Function to simulate the chatbot logic

"""

def simple_chatbot(company, user_query):
    if company in data:
        if user_query == "What is the total revenue?":
            return f"The total revenue for {company} is {data[company]['Total Revenue']}."
        elif user_query == "How has net income changed over the last year?":
            return f"The net income has changed by {data[company]['Net Income Growth']} over the last year."
        elif user_query == "What is the growth rate of total assets?":
            return f"The growth rate of total assets is {data[company]['Assets Growth']}."
        elif user_query == "What is the liabilities growth rate?":
            return f"The liabilities growth rate is {data[company]['Liabilities Growth']}."
        elif user_query == "How has cash flow from operating activities changed?":
            return f"The cash flow from operating activities has changed by {data[company]['Cash Flow Growth']}."
        else:
            return "Sorry, I can only provide information on predefined queries."
    else:
        return "Company not found."

"""## Test the chatbot with user input

"""

company_name = input("Enter the company name (Microsoft, Tesla, Apple): ")
user_question = input("Enter your question: ")
response = simple_chatbot(company_name, user_question)
print(response)